### ISSUE TITLE
I want bring NewsCrud to frontend

### ISSUE THREAD

**Issue by ThangLuuQuoc** [Laravel-Backpack/NewsCRUD#10]
Pls explain for me build front-end  from base of Backpack, use PermissionManager and NewsCRUD at my front-end.

**Comment by tabacitu** [comment]
Hi @ThangLuuQuoc ,

I'm afraid that would take quite a few pages to explain, I wouldn't know where to begin :-) 

If you haven't created any Laravel apps before I recommend going through Jeffrey Way's excellent Laracasts series. I think these ones will benefit you most:
- [Laravel from scratch](https://laracasts.com/series/laravel-5-from-scratch)
- [Build Project Flyer with me](https://laracasts.com/series/build-project-flyer-with-me)

Cheers!

**Comment by tabacitu** [comment]
PS. I've closed the issue to keep the Github nice and tidy. Feel free to reply here if you encounter Backpack issues after going through those tutorials.
