### ISSUE TITLE
Use CRUD

### ISSUE THREAD

**Issue by IvanBohonosiuk** [Laravel-Backpack/NewsCRUD#13]
Hello!

How use CRUD not news 
for example how use: Projects, categories and bids?

**Comment by tabacitu** [comment]
Hi Ivan.

Please take a look at these pages in the documentation:
- [Understanding Backpack](https://laravel-backpack.readme.io/docs)
- [Example Entity](https://laravel-backpack.readme.io/docs/crud-example)

Cheers!
