### ISSUE TITLE
What does reorder categories do?

### ISSUE THREAD

**Issue by shinokada** [Laravel-Backpack/NewsCRUD#14]
Hi, 
Since this is not a question about code, I ask here rather than in Stackoverflow.

When I reorder categories it does not reflect in the index view. So what does this reorder do actually?

![screen shot 2016-12-27 at 11 14 53 am](https://cloud.githubusercontent.com/assets/147320/21488662/df7ccd9c-cc25-11e6-955f-25fa1931374e.png)

![screen shot 2016-12-27 at 11 16 22 am](https://cloud.githubusercontent.com/assets/147320/21488671/f0e041e0-cc25-11e6-87ea-e15497c49fbb.png)

**Comment by OwenMelbz** [comment]
Hi :)

The re-order changes the ordering fields in your database table.

The Admin is purely for data management, so the order field wouldn't directly effect your admin panel, as you can click the title of the tables and it would re-order every time.

As its your column, you must handle it yourself in front-end code. So if you had a navigation on your website you might have some code like

```
$menu = Pages::orderBy('order')->get();
```

Backpack allows you to manage your data, so you can use it however you want on your application/frontend.

A good example could be, if you had SoftDeletes on a user, you'd still want to see them in your admin panel to restore them, but you wouldnt want them visible on the frontend.

This is the same for ordering or any other data, it allows you to control it all, but it wont apply the logic to itself

**Comment by shinokada** [comment]
Thanks Owen,

Categories DB has the following. Now how can I order this for the front end?

![screen shot 2016-12-28 at 12 58 51 pm](https://cloud.githubusercontent.com/assets/147320/21513560/7743fc18-ccfd-11e6-8839-f8f3ea69bd95.png)

**Comment by shinokada** [comment]
Ok, I figured it out. 

I created a Models/Category.php

```
namespace App\Models;

use Backpack\NewsCRUD\app\Models\Category as OriginalCategoryModel;

class Category extends OriginalCategoryModel
{
 /**
     * Get all category items, in a hierarchical collection.
     * Only supports 2 levels of indentation.
     */
    public static function getTree()
    {
        $category = self::orderBy('lft')->get();
        if ($category->count()) {
            foreach ($category as $k => $category_item) {
                $category_item->children = collect([]);
                foreach ($category as $i => $category_subitem) {
                    if ($category_subitem->parent_id == $category_item->id) {
                        $category_item->children->push($category_subitem);
                        // remove the subitem for the first level
                        $category = $category->reject(function ($item) use ($category_subitem) {
                            return $item->id == $category_subitem->id;
                        });
                    }
                }
            }
        }
        return $category;
    }
}
```

And then I added  this to App/Http/Controllers/ArticleController.php which displays `category`.

        $this->data['category'] = Category::getTree();

Then make a view with this:

```
@if ($category->count())
    @foreach ($category as $k => $category_item)
          @if ($category_item->children->count())
          <li class="category-item category-item-has-children {{ ($k==0)?' fistitem':'' }}">
              <a href="#">{{ $category_item->name }}</a>
              <ul class="sub-category">
                @foreach ($category_item->children as $i => $child)
                <li class="category-item"><a href="{{ $child->slug }}">{{ $child->name }}</a>
                </li>
                @endforeach
              </ul>
          </li>
          @else
          <li class="category-item">
              <a href="{{ $category_item->slug }}">{{ $category_item->name }}</a>
          </li>
          @endif
    @endforeach
@endif
```

**Comment by tabacitu** [comment]
Great! Thanks for sharing your code.

About the getTree() method, I did not implement this so far because I was pondering wether we should use our own methods or use a pre-packages solution for nested sets, like [etrepat/baum](https://github.com/etrepat/baum). But I'm not very happy that baum uses
```php
class Category extends Baum\Node {

}
```
I think it could prove limiting for some developers, that would like to implement their own inheritance.

What do you guys think? Do you know any better packages for nested sets?

**Comment by shinokada** [comment]
I am not aware of any packages, but I definitely need something here. Because I am repeating this every model and views.
