### ISSUE TITLE
Shouldn't it be use Illuminate\Foundation\Http\FormRequest;

### ISSUE THREAD

**Issue by shinokada** [Laravel-Backpack/NewsCRUD#15]
Hi,

ArticleRequest.php, CategoryRequest.php, TagRequest.php have `use App\Http\Requests\Request;`, but shouldn't it be `use Illuminate\Foundation\Http\FormRequest;`?

**Comment by tabacitu** [comment]
Hi @shinokada ,

Actually I don't think we need that one either, since ```Illuminate\Foundation\Http\FormRequest``` is already loaded in the CrudRequest class. I've just pushed a fix to eliminate them. Thanks for spotting this.

Cheers!
