### ISSUE TITLE
Unable to add article using Postgres as the database provider.

### ISSUE THREAD

**Issue by Trickierstinky** [Laravel-Backpack/NewsCRUD#16]
It seems that using Postgres as the database provider causes the create new article screen to error.

This may be a further issue on the CRUD package, however, it seems that other CRUD areas such as the ones for Categories and Pages work correctly.

I added the NewsCRUD as a package, instead of manually installing too.

The error is as follows:

`SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "FROM"
LINE 1: SHOW COLUMNS FROM `articles` WHERE Field = "status"
^ (SQL: SHOW COLUMNS FROM `articles` WHERE Field = "status") (View: /Users/mdeloughry/Projects/onecameraonly/vendor/backpack/crud/src/resources/views/fields/enum.blade.php) `

**Comment by OwenMelbz** [comment]
@tabacitu have you ever seen something like this before?

**Comment by tabacitu** [comment]
Hi @Trickierstinky ,

Seems like PosgreSQL does not support viewing the available values of the ENUM column in the db. I think your best solution would be to install the package manually, and replace that filed with a select_from_array one. I'm afraid I see no other solution.

Hope it helps.

Cheers!

**Comment by vikek** [comment]
Doesn't work with msqlite either :/
