### ISSUE TITLE
about Tags

### ISSUE THREAD

**Issue by gabva** [Laravel-Backpack/NewsCRUD#17]
Hi,

I tried newsCrud, it's very clear and easy. I had a question about tagging : 
I noticed it is not possible to add a new tag on the fly ( inside an article ). Is it a bad idea ? or this feature has simply not been implemented yet ?

Thanks :)

**Comment by OwenMelbz** [comment]
Hi,

These prebuilt cruds are just basic starting points, so you can expand them as much as you like to fulfil your requirements.

The tags are just an example of hooking up basic relationships between entities.

Its not a "tagging" system - its just a relationship link.

So feel free to create a tagging system and submit it as a PR :)

As this isn't actually a package issue, i'll close it up to keep the place more tidy, but feel free to continue adding to the thread.

**Comment by tabacitu** [comment]
It's a planned feature, but I don't know exactly when we'll get to it. 

I think this is exactly what you were looking for, right - https://github.com/Laravel-Backpack/CRUD/issues/330?

**Comment by gabva** [comment]
@OwenMelbz i know it's not an issue,  no problem,  my question was more : can it be concidered as a basic point ( and need a PR ) or is it a customization ?

@tabacitu Yes it's this feature i was looking for, thanks a lot
