### ISSUE TITLE
Fix relaction problem in Tag Model

### ISSUE THREAD

**Issue by lejubila** [Laravel-Backpack/NewsCRUD#19]
I fix relaction problem in /src/app/Models/Tag.php
I change this .....

```
public function articles()
{
	return $this->hasMany('Backpack\NewsCRUD\app\Models\Article');
}
```

with 

```
public function articles()
{
    return $this->belongsToMany('Backpack\NewsCRUD\app\Models\Article', 'article_tag');
}

```

**Comment by tabacitu** [comment]
Hi @lejubila ,

Thank you. What was the problem/error that this fixes?

Cheers!

**Comment by lejubila** [comment]
When I try to read the aticles of an tag it generates an relaction error.
Example:
$tag->articles->count().

With the fxi are returned correctly the articles of the tag.

**Comment by tabacitu** [comment]
Hi @lejubila ,

Thanks for the notice - just pushed an update with your fix.

Cheers!
