### ISSUE TITLE
Enable package auto-discovery for faster installation on L5.5

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/NewsCRUD#25]
Enable package auto-discovery for faster installation on L5.5. Eliminate 2-3 steps out of the installation process with a small composer modif:

https://medium.com/@taylorotwell/package-auto-discovery-in-laravel-5-5-ea9e3ab20518

**Comment by lloy0076** [comment]
@tabacitu - is this done?

**Comment by tabacitu** [comment]
Just have. Boom! :-)
