### ISSUE TITLE
NewsCRUD issue with category_id after composer update

### ISSUE THREAD

**Issue by morcano** [Laravel-Backpack/NewsCRUD#28]
Hi, after composer update I have issue with CRUD operations with Article on exist project.
Category_id field is disabled and when I try save or update article i get error:
Category_id field is required.
When I create new Article category field disabled. When I try edit exist article this field is also blocked.

**Comment by tabacitu** [comment]
Hi @morcano ,

How did you install NewsCrud, [option A or B](https://github.com/Laravel-Backpack/NewsCRUD#backpacknewscrud)?

**Comment by lloy0076** [comment]
@morcano - is this still an issue? If so, please reopen.
