### ISSUE TITLE
Do not hardcode the url /admin in the readme / demo.

### ISSUE THREAD

**Issue by cristianuibar** [Laravel-Backpack/NewsCRUD#29]
Use the config instead.

Use something like:

```
{{ url(config('backpack.base.route_prefix', 'admin') . '/article') }}
```

Instead of:

```
{{ url('admin/article') }}
```

**Comment by lloy0076** [comment]
Technically this isn't really a "bug" in the demo but I agree, it's not best practice.

It would be a low-hanging fruit PR as well :)

**Comment by tabacitu** [comment]
Fixed, thank you!
