### ISSUE TITLE
Failure to mention dependencies in README

### ISSUE THREAD

**Issue by joturako** [Laravel-Backpack/NewsCRUD#30]
# Bug report
Recommended installation method (file copy) doesn't work out of the box because of missing package ```cviebrock/eloquent-sluggable```
### What I did:
Using installation method A
### What I expected to happen:
Go to `admin\article` and it show a page to use
### What happened:
Site thrown error
```
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
Trait 'Cviebrock\EloquentSluggable\Sluggable' not found
```
### What I've already tried to fix it:
Install the missing package. It worked after that. Just need to mention that you have to install it in an installation step.
### Backpack, Laravel, PHP, DB version:
Base: ```^0.8.2```
Crud: ```^3.3```
Laravel: ```5.5.*```
PHP: ```7.0.25```
Mysql: ```5.7.20```

**Comment by tabacitu** [comment]
You're right @joturako . Thank you, mentioned it now!
