### ISSUE TITLE
The route group namespace is not right?

### ISSUE THREAD

**Issue by DionPotkamp** [Laravel-Backpack/NewsCRUD#47]
# Bug report

### What I did:
Installed Laravel-Backpack/NewsCRUD by method A. Replaced all namespaces and required the dependency.
### What I expected to happen:
It to work since I followed the tutorial.
### What happened:
Laravel spitting out the following error:
`Target class [App\Http\Controllers\App\Http\Controllers\Admin\ArticleCrudController] does not exist.`
### What I've already tried to fix it:
Remove `App\Http\Controllers\` from the namespace in the Route group. It now only says `Admin`. It works like it should.
### Backpack, Laravel, PHP, DB version:
Laravel: 7.24, Backpack: 4.1.*,  NewsCRUD: 4.0.1

Is this something to only I stumbled on?
If not, and this needs changing, I am willing to spend a few minutes to create a PR and change the namespace in the Route.

**Comment by tabacitu** [comment]
Indeed @DionPotkamp - the `namespace` for the route group should be `Admin` as stated in Step 5 of the Installation Method A - https://github.com/Laravel-Backpack/NewsCRUD#installation-type-a---download

Cheers!
