### ISSUE TITLE
Image Upload Issue on article 

### ISSUE THREAD

**Issue by axcel0803** [Laravel-Backpack/NewsCRUD#52]
# Bug report

### What I did:
I install news crud type (B) 
migrate 
articles categories and tags are working fine and data are restored at database 
After Clicking on browse image on Articles tab I get 404 error and cant upload image
### What I expected to happen:
I expected to browse an image and upload to dir 
### What happened:
404 error pops out and cant upload image
### What I've already tried to fix it:
change env APP_URL= to http://127.0.0.1:8000
### Backpack, Laravel, PHP, DB version:
4.1

**Comment by promatik** [comment]
Hi @axcel0803!
That popup is the the file manager, so you are probably right, that information is missing on the docs.

If you need that field, you'll need to install [Laravel-Backpack/FileManager#installation](https://github.com/Laravel-Backpack/FileManager#installation)

```bash
composer require backpack/filemanager
```

```bash
php artisan backpack:filemanager:install
```

Thank you for rising the issue, I'll add that information on the installation steps.
I'll close this issue for now, if it doesn't solve your problem please let me know ✌
