### ISSUE TITLE
Not compatible with SQLite

### ISSUE THREAD

**Issue by Polfo** [Laravel-Backpack/NewsCRUD#55]
# Bug report
When I run the backpack demo locally on my machine, and I want to edit or add an Article, the following error occurs:

```
SQLSTATE[HY000]: General error: 1 near "SHOW": syntax error 
(SQL: SHOW COLUMNS FROM `articles` WHERE Field = "status")
```

### What I expected:
Specific error message that Enum is not supported when using SQLite

### What I've already tried to fix it:
https://github.com/Laravel-Backpack/NewsCRUD/blob/b3f790eb4c1cc04376dbc4168a2f78bcec9c4294/src/app/Http/Controllers/Admin/ArticleCrudController.php#L152
modified to

```
$this->crud->addField([
    'name' => 'status',
    'label' => 'Status',
    // 'type' => 'enum', // not supported by SQLite
    'type' => 'select_from_array',
    'options'  => [
        'PUBLISHED' => 'PUBLISHED', 
        'DRAFT' => 'DRAFT',
    ],
]);
```

### Backpack, Laravel, PHP, DB version:
laravel/framework v8.1.0 
backpack/newscrud v4.0.3 
backpack/crud 4.1.22
PHP 7.4.9
SQLite 3

**Comment by pxpm** [comment]
Hello @Polfo would you like to submit a PR for it ? 

If you can't don't mind I would do it no problem at all, just let me know :)

Thanks for raising the issue!

Best,
Pedro

**Comment by Polfo** [comment]
Just closed by accident: intention was to close a window, not the issue. So reopened now.

**Comment by promatik** [comment]
Hi everyone, I've just created a PR to fix this issue on https://github.com/Laravel-Backpack/CRUD/pull/3788.
Let's keep the conversation there ✌
