### ISSUE TITLE
Add Excerpt Attribute to Article

### ISSUE THREAD

**Issue by elchroy** [Laravel-Backpack/NewsCRUD#58]
# Bug report (More like a feature request/inclusion)

### What I did:

I needed to display a list of news/blog articles but with only a small text description of the article. This is like an article excerpt, a brief summary of the main article content, which can be included in article listings, or in article page meta for SEO purposes.

### What I expected to happen:

I considered trimming the content

### What happened:

Trimming the `$article->content` did not work, as it contains HTML markup from the WYSIWYG editor which will be affected by the trimming function

### What I've already tried to fix it:

I created a migration file on my own application to add a new column `excerpt` to the `articles` table and ensured the new `excerpt` attribute is `fillable`.
See PR here - https://github.com/Laravel-Backpack/NewsCRUD/pull/57

### Backpack, Laravel, PHP, DB version:

Backpack 4.1, Laravel 8, PHP 7.4, Mysql 8.*

**Comment by promatik** [comment]
https://github.com/Laravel-Backpack/NewsCRUD/pull/57
