### ISSUE TITLE
Package Installation not compatible with Backpack 5.0

### ISSUE THREAD

**Issue by karandatwani92** [Laravel-Backpack/NewsCRUD#62]
# Bug report

#### Installation as Package

Not Compatible with Backpack 5.0
### What happened:

`Problem 1
    - backpack/newscrud 4.1.x-dev requires cviebrock/eloquent-sluggable ^7.0||^6.0||4.8 -> found cviebrock/eloquent-sluggable[4.8.0, 6.0.0, ..., 6.x-dev, 7.0.0, 7.0.1, 7.0.2, 7.x-dev] but the package is fixed to 8.0.8 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.       
    - backpack/newscrud[4.0.0, ..., v4.0.5] require backpack/crud ^4.1.0 -> found backpack/crud[4.1.0, ..., 4.1.x-dev] but it conflicts with your root composer.json require (5.0).    - backpack/newscrud v4.0.6 requires backpack/crud ^4.2.0|^4.1.0 -> found backpack/crud[4.1.0, ..., 4.1.x-dev] but it conflicts with your root composer.json require (5.0).     
    - backpack/newscrud v4.0.7 requires backpack/pro ^1.0 -> could not be found in any version, there may be a typo in the package name.
    - Root composer.json requires backpack/newscrud ^4.0 -> satisfiable by backpack/newscrud[4.0.0, ..., 4.1.x-dev].`

**Comment by tabacitu** [comment]
Hi @karandatwani92 ,

Indeed, this requires `backpack/pro` but we failed to mention that in the README. I've just added a note to say just that - https://github.com/Laravel-Backpack/NewsCRUD/commit/0e4338e8ca945383f01e44b4642a7bc71976c949

Cheers!
