### ISSUE TITLE
reorder not work

### ISSUE THREAD

**Issue by BIGITIMI** [Laravel-Backpack/NewsCRUD#8]
Hey
I did a quick backpack installation, then i tried to use the reorder feature but its not work
then i saw that my logs get full of errors and the reorder page also have the same errors in source page, but the errors not seen in the view.
i use wamp to run it localy.

this is the errors:
`
  jQuery(document).ready(function($) {

    PNotify.prototype.options.styling = "bootstrap3";
    PNotify.prototype.options.styling = "fontawesome";

    <!DOCTYPE html>
<html>
    <head>
        <meta name="robots" content="noindex,nofollow" />
        <style>
            /* Copyright (c) 2010, Yahoo! Inc. All rights reserved. Code licensed under the BSD License: http://developer.yahoo.com/yui/license.html */
            html{color:#000;background:#FFF;}body,div,dl,dt,dd,ul,ol,li,h1,h2,h3,h4,h5,h6,pre,code,form,fieldset,legend,input,textarea,p,blockquote,th,td{margin:0;padding:0;}table{border-collapse:collapse;border-spacing:0;}fieldset,img{border:0;}address,caption,cite,code,dfn,em,strong,th,var{font-style:normal;font-weight:normal;}li{list-style:none;}caption,th{text-align:left;}h1,h2,h3,h4,h5,h6{font-size:100%;font-weight:normal;}q:before,q:after{content:'';}abbr,acronym{border:0;font-variant:normal;}sup{vertical-align:text-top;}sub{vertical-align:text-bottom;}input,textarea,select{font-family:inherit;font-size:inherit;font-weight:inherit;}input,textarea,select{*font-size:100%;}legend{color:#000;}
            html { background: #eee; padding: 10px }
            img { border: 0; }
            #sf-resetcontent { width:970px; margin:0 auto; }
                        .sf-reset { font: 11px Verdana, Arial, sans-serif; color: #333 }
            .sf-reset .clear { clear:both; height:0; font-size:0; line-height:0; }
            .sf-reset .clear_fix:after { display:block; height:0; clear:both; visibility:hidden; }
            .sf-reset .clear_fix { display:inline-block; }
            .sf-reset * html .clear_fix { height:1%; }
            .sf-reset .clear_fix { display:block; }
            .sf-reset, .sf-reset .block { margin: auto }
            .sf-reset abbr { border-bottom: 1px dotted #000; cursor: help; }
            .sf-reset p { font-size:14px; line-height:20px; color:#868686; padding-bottom:20px }
            .sf-reset strong { font-weight:bold; }
            .sf-reset a { color:#6c6159; cursor: default; }
            .sf-reset a img { border:none; }
            .sf-reset a:hover { text-decoration:underline; }
            .sf-reset em { font-style:italic; }
            .sf-reset h1, .sf-reset h2 { font: 20px Georgia, "Times New Roman", Times, serif }
            .sf-reset .exception_counter { background-color: #fff; color: #333; padding: 6px; float: left; margin-right: 10px; float: left; display: block; }
            .sf-reset .exception_title { margin-left: 3em; margin-bottom: 0.7em; display: block; }
            .sf-reset .exception_message { margin-left: 3em; display: block; }
            .sf-reset .traces li { font-size:12px; padding: 2px 4px; list-style-type:decimal; margin-left:20px; }
            .sf-reset .block { background-color:#FFFFFF; padding:10px 28px; margin-bottom:20px;
                -webkit-border-bottom-right-radius: 16px;
                -webkit-border-bottom-left-radius: 16px;
                -moz-border-radius-bottomright: 16px;
                -moz-border-radius-bottomleft: 16px;
                border-bottom-right-radius: 16px;
                border-bottom-left-radius: 16px;
                border-bottom:1px solid #ccc;
                border-right:1px solid #ccc;
                border-left:1px solid #ccc;
            }
            .sf-reset .block_exception { background-color:#ddd; color: #333; padding:20px;
                -webkit-border-top-left-radius: 16px;
                -webkit-border-top-right-radius: 16px;
                -moz-border-radius-topleft: 16px;
                -moz-border-radius-topright: 16px;
                border-top-left-radius: 16px;
                border-top-right-radius: 16px;
                border-top:1px solid #ccc;
                border-right:1px solid #ccc;
                border-left:1px solid #ccc;
                overflow: hidden;
                word-wrap: break-word;
            }
            .sf-reset a { background:none; color:#868686; text-decoration:none; }
            .sf-reset a:hover { background:none; color:#313131; text-decoration:underline; }
            .sf-reset ol { padding: 10px 0; }
            .sf-reset h1 { background-color:#FFFFFF; padding: 15px 28px; margin-bottom: 20px;
                -webkit-border-radius: 10px;
                -moz-border-radius: 10px;
                border-radius: 10px;
                border: 1px solid #ccc;
            }
        </style>
    </head>
    <body>
                    <div id="sf-resetcontent" class="sf-reset">
                <h1>Whoops, looks like something went wrong.</h1>
                                        <h2 class="block_exception clear_fix">
                            <span class="exception_counter">1/1</span>
                            <span class="exception_title"><abbr title="Symfony\Component\Debug\Exception\FatalErrorException">FatalErrorException</abbr> in <a title="C:\wamp\www\backpack-demo\vendor\laravel\framework\src\Illuminate\Support\MessageBag.php line 12" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">MessageBag.php line 12</a>:</span>
                            <span class="exception_message">Maximum function nesting level of &#039;100&#039; reached, aborting!</span>
                        </h2>
                        <div class="block">
                            <ol class="traces list_exception">
       <li> in <a title="C:\wamp\www\backpack-demo\vendor\laravel\framework\src\Illuminate\Support\MessageBag.php line 12" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">MessageBag.php line 12</a></li>
       <li>at <abbr title="Symfony\Component\Debug\Exception\FatalErrorException">FatalErrorException</abbr>->__construct() in <a title="C:\wamp\www\backpack-demo\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php line 133" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">HandleExceptions.php line 133</a></li>
       <li>at <abbr title="Illuminate\Foundation\Bootstrap\HandleExceptions">HandleExceptions</abbr>->fatalExceptionFromError() in <a title="C:\wamp\www\backpack-demo\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php line 118" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">HandleExceptions.php line 118</a></li>
       <li>at <abbr title="Illuminate\Foundation\Bootstrap\HandleExceptions">HandleExceptions</abbr>->handleShutdown() in <a title="C:\wamp\www\backpack-demo\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php line 0" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">HandleExceptions.php line 0</a></li>
       <li> in <a title="C:\wamp\www\backpack-demo\vendor\composer\ClassLoader.php line 412" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">ClassLoader.php line 412</a></li>
       <li>at <abbr title=""></abbr>Composer\Autoload\includeFile() in <a title="C:\wamp\www\backpack-demo\vendor\composer\ClassLoader.php line 301" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">ClassLoader.php line 301</a></li>
       <li>at <abbr title="Composer\Autoload\ClassLoader">ClassLoader</abbr>->loadClass() in <a title="C:\wamp\www\backpack-demo\vendor\composer\ClassLoader.php line 0" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">ClassLoader.php line 0</a></li>
       <li>at <abbr title=""></abbr>spl_autoload_call() in <a title="C:\wamp\www\backpack-demo\vendor\composer\ClassLoader.php line 10" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">ClassLoader.php line 10</a></li>
       <li> in <a title="C:\wamp\www\backpack-demo\vendor\composer\ClassLoader.php line 412" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">ClassLoader.php line 412</a></li>
       <li>at <abbr title=""></abbr>Composer\Autoload\includeFile() in <a title="C:\wamp\www\backpack-demo\vendor\composer\ClassLoader.php line 301" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">ClassLoader.php line 301</a></li>
       <li>at <abbr title="Composer\Autoload\ClassLoader">ClassLoader</abbr>->loadClass() in <a title="C:\wamp\www\backpack-demo\vendor\laravel\framework\src\Illuminate\Container\Container.php line 0" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">Container.php line 0</a></li>
       <li>at <abbr title=""></abbr>spl_autoload_call() in <a title="C:\wamp\www\backpack-demo\vendor\laravel\framework\src\Illuminate\Container\Container.php line 27" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">Container.php line 27</a></li>
       <li>at <abbr title="Prologue\Alerts\AlertsServiceProvider">AlertsServiceProvider</abbr>->Prologue\Alerts\{closure}() in <a title="C:\wamp\www\backpack-demo\vendor\laravel\framework\src\Illuminate\Container\Container.php line 289" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">Container.php line 289</a></li>
       <li>at <abbr title="Illuminate\Container\Container">Container</abbr>->Illuminate\Container\{closure}() in <a title="C:\wamp\www\backpack-demo\vendor\laravel\framework\src\Illuminate\Container\Container.php line 731" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">Container.php line 731</a></li>
       <li>at <abbr title="Illuminate\Container\Container">Container</abbr>->build() in <a title="C:\wamp\www\backpack-demo\vendor\laravel\framework\src\Illuminate\Container\Container.php line 629" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">Container.php line 629</a></li>
       <li>at <abbr title="Illuminate\Container\Container">Container</abbr>->make() in <a title="C:\wamp\www\backpack-demo\vendor\laravel\framework\src\Illuminate\Foundation\Application.php line 697" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">Application.php line 697</a><…`

**Comment by BIGITIMI** [comment]
Ok i fix this by this post:
http://forum.wampserver.com/read.php?2,90631

the solution is to comment this line:
zend_extension = "d:/wamp/bin/php/php5.3.17/zend_ext/php_xdebug-2.2.0-5.3-vc9.dll"

in the php.ini file

**Comment by tabacitu** [comment]
Glad to hear you figured it out. Cheers!
